name = "inkitin-printing-hub-live"
main = "worker.js"
compatibility_date = "2026-09-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
APP_ENV = "test"
WHATSAPP_MODE = "test"
